

target 'Twitster_Example' do
    use_frameworks!
    pod 'Twitster', :path => '../'
    pod 'Fabric'
    pod 'TwitterKit'
    pod 'MBProgressHUD', '>= 1.0.0'

  target 'Twitster_Tests' do
    inherit! :search_paths

    
  end
end
